--- 
 - name: Enable OpenStack repository (CentOS)
   yum_repository:
     name: centos-openstack-wallaby
     description: "OpenStack Wallaby Repository"
     baseurl: http://mirror.stream.centos.org/SIGs/9-stream/cloud/x86_64/openstack-wallaby/
     gpgcheck: yes
     gpgkey: https://www.centos.org/keys/RPM-GPG-KEY-CentOS-Official
     enabled: yes

 - name: Install OpenStack packages
   yum: 
     name: centos-release-openstack-zed
     state: present
